---
title: "Halifax Listings"
author: "Colin Douglas"
date: "06/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)

listings <- read_csv("data/listings-clean.csv")

fsa_ns <- read_csv("canada_fsa.csv")  %>%
  select(fsa = FSA, place_name = `Place Name`, province = `FSA-Province`, area_type = AreaType) %>%
  filter(province == 12, !is.na(place_name)) %>%
  distinct()

```

## Price per Area on the Peninsula
```{r Price per Area on vs. Off, fig.width=8, fig.height=8}
peninsula_codes <- c("B3H" = "South End", 
                     "B3J" = "Downtown", 
                     "B3K" = "North End", 
                     "B3L" = "West End")

dartmouth_codes <- c(paste0("B2", c("T", "V", "W", "X", "Y", "Z")),
                     paste0("B3", c("A", "B")))
hrm_codes       <- c(paste0("B3", c("M", "N", "P", "R", "S", "T", "V", "Z")),
                     paste0("B4", c("A", "B", "C", "E", "G")))

hrm_vs_other <- listings %>%
  filter(price < 1E6, sqft_mla < 4000, # Nothing too fancy, thanks
         type %in% c("Single Family", "Condominium"),
         (!is.na(list_date) & ymd(list_date) > ymd("2020-04-01"))) %>%  # Only recent listings
  mutate(loc_bin = factor(
      case_when(
        postal_first %in% names(peninsula_codes) ~ "Halifax Peninsula",
        postal_first %in% dartmouth_codes ~ "Dartmouth",
        postal_first %in% hrm_codes ~ "HRM excl. Penin. + Dart.",
        TRUE ~ "Outside HRM"), 
      levels = c("Halifax Peninsula", "Dartmouth", "HRM excl. Penin. + Dart.", "Outside HRM")))

hrm_vs_other %>%
  ggplot(aes(x = sqft_mla, y = price)) +
  geom_point(aes(color = yday(ymd(list_date))), na.rm = TRUE) +
  labs(color = "", x = "Square Footage (MLS)", y = "List Price") +
  facet_grid(loc_bin ~ type) +
  scale_color_viridis_c(option = "plasma", 
                        direction = -1,
                        # breaks = unique(yday(ymd(listings$list_date))),
                        name = "List Date (DoY)") +
  scale_y_continuous(labels = scales::dollar) +
  geom_smooth(method = "lm", formula = y ~ x, color = "darkgrey", na.rm = TRUE)

```


## Where are the Listings?

```{r where are the listings}

postal_order <- listings %>% 
  count(postal_first) %>%
  arrange(-n) %>%
  pull(postal_first)

listings %>%
  mutate(postal_first = factor(postal_first, levels = postal_order)) %>%
  ggplot(aes(x = postal_first)) +
  geom_bar(aes(fill = substring(postal_first, 1, 2))) +
  scale_y_continuous(breaks = seq(0, 50, by = 2)) +
  scale_fill_discrete(name = '', guide = FALSE) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) 
```